### PR TITLE
Re-add Semigroup/Monoid Map instances with Warn

### PR DESCRIPTION
**Pull request by JordanMartinez**
**Description of the change**

Addresses #36 

---

**Checklist:**

- [x] Added the change to the changelog's "Unreleased" section with a reference to this PR (e.g. "- Made a change (#0000)")
- [x] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by JordanMartinez** [comment]
:ping_pong: @thomashoneyman

We might want to get more feedback on this before merging.

**Comment by thomashoneyman** [comment]
Want to copy/paste that last comment over to Discourse?

**Comment by JordanMartinez** [comment]
Sure. I've copied it over there.

**Review by thomashoneyman — APPROVED** [review]
👍, but we should leave this for another week to see if anyone has a comment wrt the warnings.

**Comment by JordanMartinez** [comment]
This PR will have been open for a week as of tomorrow (Wednesday). Since there's been no objection to dropping the `Warn` instance on `SemigroupMap`'s instances, is this ready to be merged?

**Pull request merged**
