### PR TITLE
ci test - don't merge

### PR DESCRIPTION
**Pull request by milesfrain**
Checking if CI still works on master

### CODE REVIEW

**Comment by milesfrain** [comment]
Umm... how do I trigger CI for this PR?
Patience?

**Comment by JordanMartinez** [comment]
Huh.... Is this because only the Readme was changed?

**Comment by milesfrain** [comment]
Wow, I didn't expect CI to be language-aware, but that makes sense.
This might be an issue for the cookbook where we still want CI to run when editing the readme, although it would be even better to have different tests run depending on what types of files changed.

**Comment by hdgarrood** [comment]
I think it’s probably a coincidence. Automatically inspecting a CI configuration file to figure out when CI can safely be skipped is basically impossible to do correctly, since the CI script can contain arbitrary commands.

**Comment by thomashoneyman** [comment]
I don't know why it didn't run, but CI should run on any push or pull request against master regardless of what files are changed. There's no provision for README files.

**Pull request closed without merging**
