### PR TITLE
Add Map.catMaybes function

### PR DESCRIPTION
**Pull request by drewolson**
See title.

### CODE REVIEW

**Review by hdgarrood — APPROVED** [review]
LGTM :+1:

**Comment by hdgarrood** [comment]
Actually, sorry, if we're going to add this I think we should have a `catMaybes :: Set (Maybe a) -> Set a` too.

**Comment by drewolson** [comment]
No problem, I’ll add it to set in a bit.

**Comment by drewolson** [comment]
@hdgarrood done

**Review by LiamGoodacre — APPROVED** [review]

**Pull request merged**
