### PR TITLE
Add toMap and fromMap to Data.Set. - Retry

### PR DESCRIPTION
**Pull request by milesfrain**
A rebased attempt at #21 
Hopefully this works now with updated CI

### CODE REVIEW

**Comment by milesfrain** [comment]
Looks like this is good to merge now.

I'd also be happy to see this convenience function added too, but that can be a separate PR.
```purs
annotateSet :: forall a b. (a -> b) -> Set a -> Map a b
annotateSet f = mapWithIndex (\k _ -> f k) <<< toMap
```

@np, feel free to rebase your original PR, or we can go with this one if that's more convenient.

**Comment by hdgarrood** [comment]
Looks good, but is the typelevel-prelude dependency being used at all? If not it should be removed from bower.json.

**Comment by milesfrain** [comment]
According to CI, it's unnecessary.

**Review by hdgarrood — APPROVED** [review]

**Comment by np** [comment]
I'm good with this PR.

:+1: for `annotateSet`.

**Review by thomashoneyman — APPROVED** [review]

**Comment by JordanMartinez** [comment]
Assuming CI passes, we can merge this in.

**Comment by JordanMartinez** [comment]
@milesfrain Sorry, but could you rebase this on top of current `master`? Seems CI is failing because Travis CI is still being used rather than GH Actions.

**Comment by milesfrain** [comment]
Compressed history with a force push to make future rebases easier.

Also noticed that `pulp test` fails locally on both this commit and master. So I'm not sure how master previously passed CI.

Attempting to check CI on master with #40

**Comment by JordanMartinez** [comment]
CI now fails with MonadZero deprecation notices (easy to fix) and this error:
```
1/1 TypesDoNotUnify] test/Test/Data/Map.purs:47:15

  47    arbitrary = elements $ A :| [B, C, D, E, F, G, H, I, J]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  Could not match type
  
    NonEmpty Array
  
  with type
  
    NonEmptyArray
  
  while trying to match type NonEmpty t1 SmallKey
    with type NonEmptyArray t0
  while checking that expression (NonEmpty A) [ B
                                              , C
                                              , D
                                              , E
                                              , F
                                              , G
                                              , H
                                              , I
                                              , J
                                              ]
    has type NonEmptyArray t0
  in value declaration arbSmallKey
  
  where t0 is an unknown type
        t1 is an unknown type
```

**Comment by hdgarrood** [comment]
That error is because of a breaking change in an upstream dependency (namely quickcheck). I expect it was passing the last time we merged something.

**Pull request merged**
